services:
  postgres:
    image: postgres
    container_name: unleash-db
    environment:
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unleash
    ports:
      - "5432:5432"
    networks:
      - unleash-net

  unleash:
    image: unleashorg/unleash-server
    container_name: unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://unleash_user:password@unleash-db:5432/unleash?sslmode=disable
    depends_on:
      - postgres
    networks:
      - unleash-net

networks:
  unleash-net:
    driver: bridge